worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 ipv6=off;

    server {
        listen 80;
        index index.php index.html;
        root /var/www/html/public;

        location ~ /\.ht {
            deny all;
        }

        location ~ ^/@[\w-]+/profile-picture/?$ {
            proxy_pass http://leonardo:5001;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }

        location ~ ^/api/v1/events/?.*$ {
            rewrite ^/api/v1/events/?(.*)$ /events/$1 break;
            proxy_pass http://shuttle:44999;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }

        location ~ ^/api/v1/(songs)/?$ {
            rewrite ^/api/v1/(.*)/?$ /$1 break;
            proxy_pass http://kraken:44099;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }

        location ~ ^/api/v1/storage/(songs|remixes)/?.*$ {
            rewrite ^/api/v1/storage/[a-z]*/?(.*)$ /$1 break;
            proxy_pass http://localstack:4566;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }

        location / {
            proxy_pass http://website:80;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }

        client_max_body_size 15M;
        server_tokens off;
        fastcgi_hide_header X-Powered-By;
    }
}
